### ISSUE TITLE
return value with :incomplete tuple?

### ISSUE THREAD

**Issue by bossyang** [findmypast-oss/mssqlex#10]
What is the return value with `:incomplete` tuple?

Name | Type
------ | --------
fdate  | char(10)
fpena | char(10)
fdena | char(16)

```elixir
iex(6)> Mssqlex.query(pid, stmt, [])
{:ok,
 %Mssqlex.Query{columns: nil, name: "",
  statement: "SELECT fdate, fpena, fdena FROM pse6\nWHERE fpeno = '005153' \nAND ltrim(fdate) = '106/07/13'\n"},
 %Mssqlex.Result{columns: ["fdate", "fpena", "fdena"], num_rows: 1,
  rows: [[" 106/07/13",
    {:incomplete,
     <<234, 151, 166, 238, 150, 138, 233, 170, 176, 235, 163, 165, 226, 130,
       171, 0>>, <<0>>},
    {:incomplete,
     <<235, 143, 168, 238, 162, 135, 232, 170, 168, 232, 143, 169, 226, 130,
       168, 226, 128, 160, 226, 128, 160, 226, 128, 160, 0>>, <<0>>}]]}}
```

**Comment by shdblowers** [comment]
Hi @bossyang, this is quite a confusing issue. Can you tell me what values you were expecting to come back from that query?

**Comment by bossyang** [comment]
It seems like collation issue. The MSSQL server uses `Chinese_Taiwan_Stroke_BIN`. How I change the connection setting?

Test by `sqlcmd`
```
1> SELECT fdate, fpena, fdena FROM pse6 WHERE fpeno = '002078' AND ltrim(fdate) = '106/05/09';
2> GO
fdate      fpena      fdena
---------- ---------- ----------------
 106/05/09 余淑君        行政管理處
```
[Connecting with sqlcmd](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/connecting-with-sqlcmd)

**Comment by shdblowers** [comment]
So, if you look at https://github.com/findmypast-oss/mssqlex/blob/master/lib/mssqlex/type.ex#L117

```elixir
  def decode(value, opts) when is_binary(value) do
    if opts[:preserve_encoding] || String.printable?(value) do
      value
    else
      :unicode.characters_to_binary(value, {:utf16, :little}, :unicode)
    end
  end
```

You can see that mssqlex assumes that on the value being returned from the database it expects it to be UTF16 Little Endian and that it needs to be translated into UTF8. Currently mssqlex has no options to change that.

Would changing the encoding it uses fix the problem?

**Comment by shdblowers** [comment]
Also, I should have guessed it was Taiwan with that year numbering :smile:

**Comment by jbachhardie** [comment]
Yeah that's correct, the adapter currently supports only Latin1 and Unicode, which are not coincidentally the two encodings supported by OTP's standard library. You can pass `preserve_encoding: true` as an option to avoid Mssqlex attempting conversion to Unicode but that still leaves you with an encoded binary instead of a proper string. This might be enough for your purposes, though.

Unfortunately fully implementing other legacy (i.e. non-Unicode) code pages would likely be quite challenging. I'm not even sure how well the OTP ODBC driver (which Mssqlex uses for communication with the database) deals with them. We'll happily accept pull requests on the issue though.

**Comment by bossyang** [comment]
Thank you for the quick response. 

I can assign `preserve_encoding: true` in config of MssqlEcto. Now I get

```elixir
{:ok, %Mssqlex.Result{columns: ["fdate", "fpena", "fdena"], num_rows: 1,
  rows: [[" 106/05/09",
    <<228, 189, 153, 230, 183, 145, 229, 144, 155, 32, 0, 0, 0>>,
    <<232, 161, 140, 230, 148, 191, 231, 174, 161, 231, 144, 134, 232, 153, 149,
      32, 0, 0, 0, 0, 0>>]]}}
```
Any suggestion to convert the binary to string or trim the non-printable codepoint?

workaround currently
```elixir
iex(11)> stmt4 = "SELECT fdate, rtrim(fpena) as name, rtrim(fdena) as dept FROM pse6 WHERE fpeno = '002078' AND ltrim(fdate) = '106/05/09'"
"SELECT fdate, rtrim(fpena) as name, rtrim(fdena) as dept FROM pse6 WHERE fpeno = '002078' AND ltrim(fdate) = '106/05/09'"
iex(12)> Ecto.Adapters.SQL.query(Repo, stmt4, [])

15:20:40.064 [debug] QUERY OK db=9.7ms
SELECT fdate, rtrim(fpena) as name, rtrim(fdena) as dept FROM pse6 WHERE fpeno = '002078' AND ltrim(fdate) = '106/05/09' []
bossyang> {:ok,
 %Mssqlex.Result{columns: ["fdate", "name", "dept"], num_rows: 1,
  rows: [[" 106/05/09", "余淑君", "行政管理處"]]}}
```

**Comment by jbachhardie** [comment]
I'm not intimately familiar with Chinese character encoding, much less the specific version of it that SQL Server uses, but what you are seeing might be IEx failing to determine what binaries are printable rather than them actually being unprintable. The returned binaries should be the exact data that's in the database. Have you tried passing them to `IO.puts/1` and seeing if that prints the binary? (I can't test it because I don't have a terminal set up to print Chinese)

If you want to be able to manipulate the binaries as strings in Elixir (i.e. use the `String` module) you'll need to convert them to UTF8. There's a multi-byte code page decoder for Elixir here: https://github.com/woxtu/elixir-mbcs

**Comment by bossyang** [comment]
If the column type is `VARCHAR(N)`, everything looks fine even without `preserve_encoding`.

> table psa1 with `varchar(10)` columns
```elixir
iex(34)> stmt = "SELECT fpeno, fpena, fbrda FROM psa1 WHERE fpena = ?1"
"SELECT fpeno, fpena, fbrda FROM psa1 WHERE fpena = ?1"
iex(35)> {:ok, result} = Ecto.Adapters.SQL.query(Repo, stmt, ["余淑君"])

09:33:42.194 [debug] QUERY OK db=8.8ms
SELECT fpeno, fpena, fbrda FROM psa1 WHERE fpena = ? ["余淑君"]
bossyang> {:ok,
 %Mssqlex.Result{columns: ["fpeno", "fpena", "fbrda"], num_rows: 1,
  rows: [["002078", "余淑君", "  64/07/15"]]}}
iex(36)> Enum.each result.rows, fn(row) ->
...(36)>   IO.puts row
...(36)> end
002078余淑君  64/07/15
:ok
```

So the problem is column type CHAR(N). It could be padded with spaces. Trim the trailing blanks in SQL statement and the console can print the binary.

`fpena` vs `rtrim(fdena)`
```elixir
iex(46)> stmt3 = "SELECT fdate, fpena, rtrim(fdena) FROM pse6 WHERE fpeno = ?1 AND ltrim(fdate) = ?2"
"SELECT fdate, fpena, rtrim(fdena) FROM pse6 WHERE fpeno = ?1 AND ltrim(fdate) = ?2"
iex(47)> Ecto.Adapters.SQL.query(Repo, stmt3, ["002078", "106/05/09"])

09:53:08.122 [debug] QUERY OK db=12.4ms
SELECT fdate, fpena, rtrim(fdena) FROM pse6 WHERE fpeno = ? AND ltrim(fdate) = ? ["002078", "106/05/09"]
bossyang> {:ok,
 %Mssqlex.Result{columns: ["fdate", "fpena", ""], num_rows: 1,
  rows: [[" 106/05/09",
    {:incomplete,
     <<235, 183, 164, 238, 154, 153, 233, 134, 183, 233, 131, 165, 226, 130,
       155, 0>>, <<0>>}, "行政管理處"]]}}
```
>  `preserve_encoding: false` here, too

**Comment by jbachhardie** [comment]
I think you've definitely found the root cause there, `char(n)` type data in the database would be padded with null bytes, messing up the naive multi-byte decoding that Elixir does (just assumes everything is either valid UTF8 or non-printable). You could trim them at the query level (as you've done), write a function to trim them at app level (although manipulating raw bytes in Elixir is a bit cumbersome), convert them to valid UTF8, or just manipulate them as binaries without worrying about the fact elixir's inspector prints them as series of bytes instead of characters with spacing at the end.

From the point of view of the adapter, I'm not sure if we can do anything here. The null bytes are in the database and do form part of a valid string, it's just that Elixir has trouble manipulating that encoding. If we make the adapter trim null bytes from `char(n)` columns that will be unexpected behaviour for many users that expect returns from a `char(n)` column to always be of length `n` exactly.

What do you think represents expected behaviour from the adapter in this case?

**Comment by bossyang** [comment]
@jbachhardie Thank you for your detailed explanation. After all I can manipulate data in raw SQL. But it is still a problem in MssqlEcto schema, right?

Anyway, you may close this issue any time.

ps. I just try to rewrite my little Hubot project with Hedwig. Unfortunately, the legacy database kills me. In Node.js, it is easy to use mssql with [TDS](http://tediousjs.github.io/tedious/index.html) driver. No need to setup in runtime environment (Oracle Linux 6.x), like ODBC manager.

```coffee
sql = require('mssql')
s   = require('underscore.string')
# skip some lines ~~
script = "SELECT fdate,
  fpena,
  fdena,
  fchna,
  fquan,
  fpdun,
  fextr,
  fsttm,
  fentm,
  f0lin
  FROM pse6
  WHERE fpeno = @emp_no
    AND ltrim(fdate) like @yymm"
# skip some lines ~~
connection = new sql.Connection config, (err) ->
      ps = new sql.PreparedStatement connection
      ps.input 'yymm', sql.VarChar(10)
      ps.input 'emp_no', sql.VarChar(10)
      ps.prepare script, (err) ->
        res.reply err.message if err

        ps.execute yymm: month, emp_no: emp, (err, recordsets) ->
          res.reply err.message if err

          if recordsets.length > 0
            text = "#{emp}出勤單據紀錄：\n"
            for r in recordsets
              # I think the underscore.string convert the null to space here
              note_name = s(r.fchna).trim().rpad(3, '　').value()
              start = s(r.fsttm).pad(2).value()
              end   = s(r.fentm).pad(2).value()
              qty   = s(r.fquan).pad(3).value()
              text += "#{r.fdate}, #{note_name}, #{qty}#{r.fpdun.trim()}, #{start}-#{end}, #{r.f0lin}\n"

            res.reply text

```

**Comment by jbachhardie** [comment]
Yeah. There's a pure-Elixir TDS driver that doesn't require any runtime dependencies at https://github.com/livehelpnow/tds but it's not maintained and (in our experience) rather buggy. Until someone decides to do a better TDS implementation we're stuck accessing SQL Server using Microsoft's own drivers, which I agree they do not make easy to install on many operating systems.

You can easily use rtrim/ltrim in Ecto queries, by the way, if you still want to pursue this: 
```elixir
from p in Pse6,
  where: p.fpeno == "002078" and fragment("ltrim(?)", p.fdate) == "106/05/09",
  select: {p.fdate, p.fpena, fragment("rtrim(?)", p.fdena)}
```
